#ifndef _LOONGARCH64_H
#define _LOONGARCH64_H
#define EXCEPT_LOONGARCH_INT   0
#define EXCEPT_LOONGARCH_PIL   1
#define EXCEPT_LOONGARCH_PIS   2
#define EXCEPT_LOONGARCH_PIF   3
#define EXCEPT_LOONGARCH_PME   4
#define EXCEPT_LOONGARCH_PNR   5
#define EXCEPT_LOONGARCH_PNX   6
#define EXCEPT_LOONGARCH_PPI   7
#define EXCEPT_LOONGARCH_ADE   8
#define EXCEPT_LOONGARCH_ALE   9
#define EXCEPT_LOONGARCH_BCE   10
#define EXCEPT_LOONGARCH_SYS   11
#define EXCEPT_LOONGARCH_BRK   12
#define EXCEPT_LOONGARCH_INE   13
#define EXCEPT_LOONGARCH_IPE   14
#define EXCEPT_LOONGARCH_FPD   15
#define EXCEPT_LOONGARCH_SXD   16
#define EXCEPT_LOONGARCH_ASXD  17
#define EXCEPT_LOONGARCH_FPE   18
#define EXCEPT_LOONGARCH_WPE   19
#define EXCEPT_LOONGARCH_BTD   20
#define EXCEPT_LOONGARCH_BTE   21
#define EXCEPT_LOONGARCH_GSPR  22
#define EXCEPT_LOONGARCH_HVC   23
#define EXCEPT_LOONGARCH_GCXC  24
#define MAX_LOONGARCH_EXCEPTION 64
#define MAX_LOONGARCH_INTERRUPT  16
#endif
