#ifndef _MACHINE_H
#define _MACHINE_H
#define SEC_PEI_TEMP_RAM_BASE 0x10000
#define SEC_PEI_TEMP_RAM_SIZE 0x80000
#define LOONGARCH_EXCEPTION_VECTOR_BASE_ADDRESS SEC_PEI_TEMP_RAM_BASE

#define FW_BASE_ADDRESS       0x1c000000

#define CPU_MAX_LOGICAL_PROCESSOR_NUMBER 256
#endif
